version: '3.8'

services:
    icm-mysql-old:
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
            - MYSQL_DATABASE=${OLD_DB}
            - MYSQL_USER=${OLD_DB}
            - MYSQL_PASSWORD=${PW}
        image: mysql:5.7
        volumes:
            # - ./data-old:/var/lib/mysql:Z
            # - ./data-old:/docker-entrypoint-initdb.d/1.sql
            - ./config-old/mysql/mysql-dump/blugiant_icm_inv.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - "3307:3307"
        restart: always
        networks:
            - icm
    drupal-old:
        depends_on: 
            - icm-mysql-old
        volumes:
            - ./drupal-old:/var/www/html
            - ./config-old/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "7080:80"
        environment:
            - DRUPAL_DATABASE_HOST=icm-mysql-old
            - DRUPAL_DATABASE_PORT=3306
            - DRUPAL_DATABASE_NAME=${OLD_DB}
            - DRUPAL_DATABASE_USERNAME=${OLD_DB}
            - DRUPAL_DATABASE_PASSWORD=${PW}
        image: drupal:7.69
        restart: always
        networks:
            - icm
    phpmyadmin-old:
        depends_on: 
            - icm-mysql-old
        networks:
            - icm
        environment:
            - PMA_HOST=icm-mysql-old
            - PMA_USER=${OLD_DB}
            - PMA_PASSWORD=${PW}
            - PHP_UPLOAD_MAX_FILESIZE=1G
            - PHP_MAX_INPUT_VARS=1
        ports:
            - "7001:80"
        image: phpmyadmin/phpmyadmin
        restart: always
    icm-mysql:
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
            - MYSQL_DATABASE=${DB}
            - MYSQL_USER=${DB}
            - MYSQL_PASSWORD=${PW}
        image: mysql:latest
        volumes:
            - ./data:/var/lib/mysql:Z
        #     - ./config/mysql/mysql-dump/blugiant_icm_inv.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - "3308:3308"
        restart: always
        networks:
            - icm
    icm-drupal:
        depends_on: 
            - icm-mysql
        build: ./config
        volumes:
            - ./drupal/web:/var/www/html
            - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - "8080:80"
        environment:
            - DRUPAL_DATABASE_HOST=icm-mysql
            - DRUPAL_DATABASE_PORT=3306
            - DRUPAL_DATABASE_NAME=${DB}
            - DRUPAL_DATABASE_USERNAME=${DB}
            - DRUPAL_DATABASE_PASSWORD=${PW}
        image: drupal:8.9.14-apache
        restart: always
        networks:
            - icm
    phpmyadmin:
        depends_on: 
            - icm-mysql
        networks:
            - icm
        environment:
            - PMA_HOST=icm-mysql
            - PMA_USER=${DB}
            - PMA_PASSWORD=${PW}
            - PHP_UPLOAD_MAX_FILESIZE=1G
            - PHP_MAX_INPUT_VARS=1
        ports:
            - "8001:80"
        image: phpmyadmin/phpmyadmin
        restart: always
networks:
  icm: