version: '3.8'

services:
  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
      - MYSQL_DATABASE=${OLD_DB}
      - MYSQL_USER=${OLD_DB}
      - MYSQL_PASSWORD=${PW}
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql:Z
    #     - ./config/mysql/mysql-dump/blugiant_icm_inv.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - '3308:3308'
    restart: always
    networks:
      - icm
  drupal:
    depends_on:
      - icm-mysql
    build: ./config
    volumes:
      - ./drupal/web:/var/www/html
      - ./config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./drupal/composer.json:/opt/drupal/composer.json
    ports:
      - '8080:80'
    environment:
      - DRUPAL_DATABASE_HOST=icm-mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_DATABASE_NAME=${OLD_DB}
      - DRUPAL_DATABASE_USERNAME=${OLD_DB}
      - DRUPAL_DATABASE_PASSWORD=${PW}
    image: drupal:9.2.0-apache
    restart: always
    networks:
      - icm
  phpmyadmin:
    depends_on:
      - icm-mysql
    networks:
      - icm
    environment:
      - PMA_HOST=icm-mysql
      - PMA_USER=${OLD_DB}
      - PMA_PASSWORD=${PW}
      - PHP_UPLOAD_MAX_FILESIZE=600M
      - UPLOAD_LIMIT=600M
      - PHP_MAX_INPUT_VARS=1
    ports:
      - '8001:80'
    image: phpmyadmin/phpmyadmin
    restart: always
networks:
  icm:
